apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  labels:
    app: sonarqube
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - image: sonarqube:latest
        imagePullPolicy: Always
        name: sonarqube
        ports:
        - containerPort: 9000
          protocol: TCP
