apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube
    service: sonarqube
  name: sonarqube
spec:
  type: LoadBalancer
  ports:
    - name: sonar
      port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonarqube
